name: graph-generation
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0
  - pytorch-cuda=11.8
  - pyg=2.3.1
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - networkx=3.1
  - graph-tool=2.58
  - pygsp=0.5.1
  - matplotlib=3.7.2
  - hydra-core=1.3.2
  - hydra-submitit-launcher=1.2.0
  - wandb=0.15.9
  - pyemd=0.5.1
  - tqdm=4.66.1
  - python-dotenv=1.0.0
